package org.jbnd.binding;

import org.jbnd.ValidationException;


/**
 * An interface for objects used by <tt>Binding</tt>s to handle validation
 * exceptions occurring at attempted editing, and to determine if or not the
 * invalid value should be "pushed" (set regardless of it's invalidity).
 * 
 * @author Florijan Stamenkovic (flor385@mac.com)
 * @version 1.0, Sep 20, 2007
 * @see Binding
 * @see Binding#edit(int, String, Object)
 * @see Binding#setValidationHandler(ValidationHandler)
 */
public interface ValidationHandler{
	
	/**
	 * Does whatever is appropriate with the generated exception; this can imply
	 * disregarding it, informing the user about it in some way, or re-throwing
	 * it.
	 * 
	 * @param exception The exception generated by a <tt>Binding</tt> after an
	 *            attempt to set an invalid value through it's editing method.
	 * @return If or not the value should be pushed, regardless of it's
	 *         invalidity.
	 * @throws ValidationException The same exception, optionally re-thrown.
	 * @see Binding#edit(int, String, Object)
	 * @see Binding#setValidationHandler(ValidationHandler)
	 */
	public boolean handleException(ValidationException exception) throws ValidationException;
}
